version: "2"
services:
  db:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=root
      volumes:
          - ./database:/var/lib/mysql
      ports:
          - 3306:3306
      networks:
          - default
      restart: always
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        MYSQL_ROOT_PASSWORD: root          
        restart: always
      ports:
          - 8083:80
      volumes:
          - /db-data
      links:
          - db
      restart: always          
networks:
    default:
        # use the bridge driver, but enable IPv6
        driver: bridge